### ISSUE TITLE
java.lang.NoClassDefFoundError: com/intellij/json/JsonFileType

### ISSUE THREAD

**Issue by dwoldrich** [jballant/CommonJSAutoComplete#1] opened 2015-03-05 00:30 UTC
Plugin got the following exception whenever I attempt to autocomplete (as I type 'require') using plugin version 0.1.1 on IntelliJ 13.1.6:

com/intellij/json/JsonFileType: com/intellij/json/JsonFileType
java.lang.NoClassDefFoundError: com/intellij/json/JsonFileType
    at completion.JSRequirePathFinder$1.isJSFile(JSRequirePathFinder.java:185)
    at completion.JSRequirePathFinder$1.visitFile(JSRequirePathFinder.java:165)
    at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:124)
    at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:243)
    at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:275)
    at completion.JSRequirePathFinder.findFilePathForNameHelper(JSRequirePathFinder.java:129)
    at completion.JSRequirePathFinder.findPathsForVarName(JSRequirePathFinder.java:77)
    at completion.JSRequireCompletionProvider.addCompletions(JSRequireCompletionProvider.java:83)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at completion.JSRequireCompletionContributer.fillCompletionVariants(JSRequireCompletionContributer.java:34)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:75)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:769)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$900(CompletionProgressIndicator.java:84)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:751)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

**Comment by jballant** [comment] 2015-03-05 16:33
Thanks for letting me know, I'll get IntelliJ 13.1.6 and take a look.

**Comment by dwoldrich** [comment] 2015-03-05 16:59
Cheers!  I hope your plugin gets officially adopted by JetBrains, it's very slick.

**Comment by jballant** [comment] 2015-03-05 19:21
Thanks!

The problem is the JSON language library changed in IntelliJ 14, which I didn't realize. 

I now need to have a different version of the plugin for IntelliJ 13 / WebStorm 7 that uses the old library, and another version for IntelliJ 14 / WebStorm 8.

I have created a branch with the old JSON language library, please feel free to try it out before I publish it:
https://github.com/jballant/CommonJSAutoComplete/raw/intellij-131-version/CommonJSAutoComplete.jar

Just download the JAR and install it from disk using the IDEA "Plugins" menu, and let me know how it goes.

**Comment by dwoldrich** [comment] 2015-03-06 10:15
Yep, that fixed it, I'm seeing autocompletes and no more exceptions in the console on 13.1.6 with the jar you provided.  Bummer the JSON library changed on you, would it be worth it to bundle with a 3rd party library instead?

Hey, while I got you, would it be possible to get a config to enable emitting double quotes in the require's autocomplete instead of single quotes?  Our linter is set to complain when we use single-quoted strings and I always have to change the string myself.  I'll file a new enhancement request if you think it's something worth doing.  Thanks again!

**Comment by jballant** [comment] 2015-03-06 15:50
I hadn't thought of linting issues with single quotes--the option to specify makes sense. I can definitely add a feature for that in the next release.

Here is an enhancement issue to track it if you like:
https://github.com/jballant/CommonJSAutoComplete/issues/2

**Comment by jballant** [comment] 2015-03-06 17:15
New versions with compatibility restrictions are up. Version 0.1.2 is for IntelliJ 13.1 / WebStorm 7 and 0.1.3 is for IntelliJ 14 / WebStorm 8.  Closing.

**Closed as completed by jballant** 2015-03-06 17:15 UTC
Labels: bug
